- hosts: gitlab
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    myagkikh
  roles:
   - gitlab

  environment:
     http_proxy: http://weltonauto.com:8888
     https_proxy: http://weltonauto.com:8888
